parameters:
    app.api_key: '%env(APP_API_KEY)%'

services:
    App\Interface\IpCountryResolverInterface: '@App\Service\IplocateIpCountryResolver'

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\EventSubscriber\ApiRequestSubscriber:
        arguments:
            $apiKey: '%app.api_key%'